defaults:
  - base
  - _self_

policy:
  _target_: quest.algos.diffusion_policy.DiffusionPolicy
  diffusion_model:
    _target_: quest.algos.diffusion_policy.DiffusionModel
    noise_scheduler: 
      _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
      num_train_timesteps: ${algo.diffusion_train_steps}
      beta_schedule: squaredcos_cap_v2
    action_dim: ${task.shape_meta.action_dim}
    global_cond_dim: ${eval:'${algo.embed_dim} + ${algo.lang_emb_dim}'}
    diffusion_step_emb_dim: ${algo.diffusion_step_emb_dim}
    down_dims: [256,512,1024]
    ema_power: 0.75
    skill_block_size: ${algo.skill_block_size}
    diffusion_inf_steps: ${algo.diffusion_inf_steps}
    device: ${device}
    n_guide_steps: ${algo.n_guide_steps}
    guidance_scale: ${algo.guidance_scale}
    guide_fn:
      _target_: quest.algos.diffusion_policy.wall_loss_fn
      _partial_: true
      safe_dist: 0.07
      delta_t: 1.0
    verbose: true
  action_horizon: ${algo.action_horizon}
  obs_reduction: cat
  device: ${device}


name: diffusion_policy

lr: 0.0001
weight_decay: 0.0001

lowdim_embed_dim: 128
image_embed_dim: 256 
pc_embed_dim: 256
diffusion_step_emb_dim: 256
lang_emb_dim: 256 # clip embedding size
embed_dim: 256

skill_block_size: 16 # this is input sequence length to encoder

# defining here for ease
diffusion_train_steps: 100
diffusion_inf_steps: 10
n_guide_steps: 2 # set to 0 if you don't want to use guided diffusion
guidance_scale: 0.1

action_horizon: 2 # mpc horizon for execution

frame_stack: 1

dataset:
  seq_len: ${algo.skill_block_size}
  frame_stack: ${algo.frame_stack}
  obs_seq_len: 1
  lowdim_obs_seq_len: null
  load_obs_for_pretrain: true
  load_next_obs: false